type User {
    id: ID!
    name: String!
    lastname: String
    email: String!
    password: String
    role: Role!
    active: Boolean
    phone: String
    addresses: [Address]
    policy: Boolean
    image: String
    profile: String
    registerUser: String
    updateUser: String
    registerDate: String
    updateDate: String
}

type Address {
    c_pais: String!
    d_pais: String!
    c_estado: String!
    d_estado: String!
    c_mnpio: String!
    d_mnpio: String!
    c_ciudad: String
    d_ciudad: String
    d_asenta: String!
    directions: String!
    phone: String
    references: String
    d_codigo: String!
    dir_invoice: Boolean
    dir_delivery: Boolean
    dir_delivery_main: Boolean
    outdoorNumber: String
    interiorNumber: String
}